# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-config
# data:
#   APP_MESSAGE: "Hello from myfirstapp via ConfigMap!"apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  index.html: |
    <html>
    <body>
      <h1>Hello from myfirstapp via ConfigMap!</h1>
    </body>
    </html>



