# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}
# spec:
#   selector:
#     app: {{ .Release.Name }}
#   ports:
#   - port: {{ .Values.service.port }}
#     targetPort: 80
#   type: {{ .Values.service.type }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
