# replicaCount: 4

# image:
#   repository: nginx
#   tag: latest
#   pullPolicy: IfNotPresent

# service:
#   type: ClusterIP
#   port: 80

replicaCount: 4

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP   # can be ClusterIP, NodePort, or LoadBalancer
  port: 80
  # nodePort: 30080  # uncomment if using NodePort

ui:
  title: "MyFirstApp"
  header: "Hello from myfirstapp via ConfigMap!"
  subheader: "ðŸš€ Deployed with Argo CD & Helm"
  backgroundColor: "#f0f8ff"   # light blue
  headerColor: "#2e8b57"       # sea green
  subheaderColor: "#4682b4"    # steel blue
